name: release

on:
  push:
    tags: ["v*"]  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: ghalactic/github-release-from-tag@v5
        with:
          prerelease: "false"
          draft: "true"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "{{ cookiecutter.python_version }}"

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Publish to TestPyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish --build -r test-pypi -u __token__ -p {% raw %}${{ secrets.TEST_PYPI_API_TOKEN }}{% endraw %}

      - name: Test install from TestPyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            {{ cookiecutter.__package_slug }}

      - name: Publish to PyPI
        run: |
          poetry publish --build -u __token__ -p {% raw %}${{ secrets.PYPI_API_TOKEN }}{% endraw %}
