name: test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v1
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/ --cov={{ cookiecutter.__package_slug }} --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml   # coverage report
